// Code generated by protoc-gen-go. DO NOT EDIT.
// source: pb/order.proto

package pb

import (
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

// -------------------- Objects --------------------
type Address struct {
	ZipCode              string   `protobuf:"bytes,1,opt,name=zip_code,json=zipCode,proto3" json:"zip_code,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Address) Reset()         { *m = Address{} }
func (m *Address) String() string { return proto.CompactTextString(m) }
func (*Address) ProtoMessage()    {}
func (*Address) Descriptor() ([]byte, []int) {
	return fileDescriptor_e4944acb1d14eb6b, []int{0}
}

func (m *Address) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Address.Unmarshal(m, b)
}
func (m *Address) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Address.Marshal(b, m, deterministic)
}
func (m *Address) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Address.Merge(m, src)
}
func (m *Address) XXX_Size() int {
	return xxx_messageInfo_Address.Size(m)
}
func (m *Address) XXX_DiscardUnknown() {
	xxx_messageInfo_Address.DiscardUnknown(m)
}

var xxx_messageInfo_Address proto.InternalMessageInfo

func (m *Address) GetZipCode() string {
	if m != nil {
		return m.ZipCode
	}
	return ""
}

type DeliveryInformation struct {
	Address              *Address `protobuf:"bytes,1,opt,name=address,proto3" json:"address,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *DeliveryInformation) Reset()         { *m = DeliveryInformation{} }
func (m *DeliveryInformation) String() string { return proto.CompactTextString(m) }
func (*DeliveryInformation) ProtoMessage()    {}
func (*DeliveryInformation) Descriptor() ([]byte, []int) {
	return fileDescriptor_e4944acb1d14eb6b, []int{1}
}

func (m *DeliveryInformation) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_DeliveryInformation.Unmarshal(m, b)
}
func (m *DeliveryInformation) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_DeliveryInformation.Marshal(b, m, deterministic)
}
func (m *DeliveryInformation) XXX_Merge(src proto.Message) {
	xxx_messageInfo_DeliveryInformation.Merge(m, src)
}
func (m *DeliveryInformation) XXX_Size() int {
	return xxx_messageInfo_DeliveryInformation.Size(m)
}
func (m *DeliveryInformation) XXX_DiscardUnknown() {
	xxx_messageInfo_DeliveryInformation.DiscardUnknown(m)
}

var xxx_messageInfo_DeliveryInformation proto.InternalMessageInfo

func (m *DeliveryInformation) GetAddress() *Address {
	if m != nil {
		return m.Address
	}
	return nil
}

type PaymentInformation struct {
	Token                string   `protobuf:"bytes,1,opt,name=token,proto3" json:"token,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *PaymentInformation) Reset()         { *m = PaymentInformation{} }
func (m *PaymentInformation) String() string { return proto.CompactTextString(m) }
func (*PaymentInformation) ProtoMessage()    {}
func (*PaymentInformation) Descriptor() ([]byte, []int) {
	return fileDescriptor_e4944acb1d14eb6b, []int{2}
}

func (m *PaymentInformation) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_PaymentInformation.Unmarshal(m, b)
}
func (m *PaymentInformation) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_PaymentInformation.Marshal(b, m, deterministic)
}
func (m *PaymentInformation) XXX_Merge(src proto.Message) {
	xxx_messageInfo_PaymentInformation.Merge(m, src)
}
func (m *PaymentInformation) XXX_Size() int {
	return xxx_messageInfo_PaymentInformation.Size(m)
}
func (m *PaymentInformation) XXX_DiscardUnknown() {
	xxx_messageInfo_PaymentInformation.DiscardUnknown(m)
}

var xxx_messageInfo_PaymentInformation proto.InternalMessageInfo

func (m *PaymentInformation) GetToken() string {
	if m != nil {
		return m.Token
	}
	return ""
}

type OrderLineItem struct {
	MenuItemId           string   `protobuf:"bytes,1,opt,name=menu_item_id,json=menuItemId,proto3" json:"menu_item_id,omitempty"`
	Quantity             int64    `protobuf:"varint,2,opt,name=quantity,proto3" json:"quantity,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *OrderLineItem) Reset()         { *m = OrderLineItem{} }
func (m *OrderLineItem) String() string { return proto.CompactTextString(m) }
func (*OrderLineItem) ProtoMessage()    {}
func (*OrderLineItem) Descriptor() ([]byte, []int) {
	return fileDescriptor_e4944acb1d14eb6b, []int{3}
}

func (m *OrderLineItem) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_OrderLineItem.Unmarshal(m, b)
}
func (m *OrderLineItem) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_OrderLineItem.Marshal(b, m, deterministic)
}
func (m *OrderLineItem) XXX_Merge(src proto.Message) {
	xxx_messageInfo_OrderLineItem.Merge(m, src)
}
func (m *OrderLineItem) XXX_Size() int {
	return xxx_messageInfo_OrderLineItem.Size(m)
}
func (m *OrderLineItem) XXX_DiscardUnknown() {
	xxx_messageInfo_OrderLineItem.DiscardUnknown(m)
}

var xxx_messageInfo_OrderLineItem proto.InternalMessageInfo

func (m *OrderLineItem) GetMenuItemId() string {
	if m != nil {
		return m.MenuItemId
	}
	return ""
}

func (m *OrderLineItem) GetQuantity() int64 {
	if m != nil {
		return m.Quantity
	}
	return 0
}

type OrderLineItems struct {
	LineItems            []*OrderLineItem `protobuf:"bytes,1,rep,name=line_items,json=lineItems,proto3" json:"line_items,omitempty"`
	XXX_NoUnkeyedLiteral struct{}         `json:"-"`
	XXX_unrecognized     []byte           `json:"-"`
	XXX_sizecache        int32            `json:"-"`
}

func (m *OrderLineItems) Reset()         { *m = OrderLineItems{} }
func (m *OrderLineItems) String() string { return proto.CompactTextString(m) }
func (*OrderLineItems) ProtoMessage()    {}
func (*OrderLineItems) Descriptor() ([]byte, []int) {
	return fileDescriptor_e4944acb1d14eb6b, []int{4}
}

func (m *OrderLineItems) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_OrderLineItems.Unmarshal(m, b)
}
func (m *OrderLineItems) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_OrderLineItems.Marshal(b, m, deterministic)
}
func (m *OrderLineItems) XXX_Merge(src proto.Message) {
	xxx_messageInfo_OrderLineItems.Merge(m, src)
}
func (m *OrderLineItems) XXX_Size() int {
	return xxx_messageInfo_OrderLineItems.Size(m)
}
func (m *OrderLineItems) XXX_DiscardUnknown() {
	xxx_messageInfo_OrderLineItems.DiscardUnknown(m)
}

var xxx_messageInfo_OrderLineItems proto.InternalMessageInfo

func (m *OrderLineItems) GetLineItems() []*OrderLineItem {
	if m != nil {
		return m.LineItems
	}
	return nil
}

// -------------------- Commands --------------------
type CreateOrder struct {
	Id                   string               `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	PaymentInformation   *PaymentInformation  `protobuf:"bytes,2,opt,name=payment_information,json=paymentInformation,proto3" json:"payment_information,omitempty"`
	DeliveryInformation  *DeliveryInformation `protobuf:"bytes,3,opt,name=delivery_information,json=deliveryInformation,proto3" json:"delivery_information,omitempty"`
	OrderLineItems       *OrderLineItems      `protobuf:"bytes,4,opt,name=order_line_items,json=orderLineItems,proto3" json:"order_line_items,omitempty"`
	XXX_NoUnkeyedLiteral struct{}             `json:"-"`
	XXX_unrecognized     []byte               `json:"-"`
	XXX_sizecache        int32                `json:"-"`
}

func (m *CreateOrder) Reset()         { *m = CreateOrder{} }
func (m *CreateOrder) String() string { return proto.CompactTextString(m) }
func (*CreateOrder) ProtoMessage()    {}
func (*CreateOrder) Descriptor() ([]byte, []int) {
	return fileDescriptor_e4944acb1d14eb6b, []int{5}
}

func (m *CreateOrder) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_CreateOrder.Unmarshal(m, b)
}
func (m *CreateOrder) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_CreateOrder.Marshal(b, m, deterministic)
}
func (m *CreateOrder) XXX_Merge(src proto.Message) {
	xxx_messageInfo_CreateOrder.Merge(m, src)
}
func (m *CreateOrder) XXX_Size() int {
	return xxx_messageInfo_CreateOrder.Size(m)
}
func (m *CreateOrder) XXX_DiscardUnknown() {
	xxx_messageInfo_CreateOrder.DiscardUnknown(m)
}

var xxx_messageInfo_CreateOrder proto.InternalMessageInfo

func (m *CreateOrder) GetId() string {
	if m != nil {
		return m.Id
	}
	return ""
}

func (m *CreateOrder) GetPaymentInformation() *PaymentInformation {
	if m != nil {
		return m.PaymentInformation
	}
	return nil
}

func (m *CreateOrder) GetDeliveryInformation() *DeliveryInformation {
	if m != nil {
		return m.DeliveryInformation
	}
	return nil
}

func (m *CreateOrder) GetOrderLineItems() *OrderLineItems {
	if m != nil {
		return m.OrderLineItems
	}
	return nil
}

// -------------------- Events --------------------
type OrderCreated struct {
	Id                   string               `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	PaymentInformation   *PaymentInformation  `protobuf:"bytes,2,opt,name=payment_information,json=paymentInformation,proto3" json:"payment_information,omitempty"`
	DeliveryInformation  *DeliveryInformation `protobuf:"bytes,3,opt,name=delivery_information,json=deliveryInformation,proto3" json:"delivery_information,omitempty"`
	OrderLineItems       *OrderLineItems      `protobuf:"bytes,4,opt,name=order_line_items,json=orderLineItems,proto3" json:"order_line_items,omitempty"`
	XXX_NoUnkeyedLiteral struct{}             `json:"-"`
	XXX_unrecognized     []byte               `json:"-"`
	XXX_sizecache        int32                `json:"-"`
}

func (m *OrderCreated) Reset()         { *m = OrderCreated{} }
func (m *OrderCreated) String() string { return proto.CompactTextString(m) }
func (*OrderCreated) ProtoMessage()    {}
func (*OrderCreated) Descriptor() ([]byte, []int) {
	return fileDescriptor_e4944acb1d14eb6b, []int{6}
}

func (m *OrderCreated) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_OrderCreated.Unmarshal(m, b)
}
func (m *OrderCreated) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_OrderCreated.Marshal(b, m, deterministic)
}
func (m *OrderCreated) XXX_Merge(src proto.Message) {
	xxx_messageInfo_OrderCreated.Merge(m, src)
}
func (m *OrderCreated) XXX_Size() int {
	return xxx_messageInfo_OrderCreated.Size(m)
}
func (m *OrderCreated) XXX_DiscardUnknown() {
	xxx_messageInfo_OrderCreated.DiscardUnknown(m)
}

var xxx_messageInfo_OrderCreated proto.InternalMessageInfo

func (m *OrderCreated) GetId() string {
	if m != nil {
		return m.Id
	}
	return ""
}

func (m *OrderCreated) GetPaymentInformation() *PaymentInformation {
	if m != nil {
		return m.PaymentInformation
	}
	return nil
}

func (m *OrderCreated) GetDeliveryInformation() *DeliveryInformation {
	if m != nil {
		return m.DeliveryInformation
	}
	return nil
}

func (m *OrderCreated) GetOrderLineItems() *OrderLineItems {
	if m != nil {
		return m.OrderLineItems
	}
	return nil
}

func init() {
	proto.RegisterType((*Address)(nil), "pb.Address")
	proto.RegisterType((*DeliveryInformation)(nil), "pb.DeliveryInformation")
	proto.RegisterType((*PaymentInformation)(nil), "pb.PaymentInformation")
	proto.RegisterType((*OrderLineItem)(nil), "pb.OrderLineItem")
	proto.RegisterType((*OrderLineItems)(nil), "pb.OrderLineItems")
	proto.RegisterType((*CreateOrder)(nil), "pb.CreateOrder")
	proto.RegisterType((*OrderCreated)(nil), "pb.OrderCreated")
}

func init() { proto.RegisterFile("pb/order.proto", fileDescriptor_e4944acb1d14eb6b) }

var fileDescriptor_e4944acb1d14eb6b = []byte{
	// 341 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0xe4, 0x93, 0x51, 0x4f, 0xea, 0x30,
	0x18, 0x86, 0xb3, 0x71, 0xce, 0x01, 0xbe, 0x71, 0x96, 0x73, 0x0a, 0x51, 0xf4, 0x8a, 0x34, 0x9a,
	0x10, 0x2f, 0xd0, 0xe0, 0x2d, 0x37, 0x8a, 0x89, 0xc1, 0x68, 0x34, 0xfd, 0x03, 0xcb, 0x66, 0x3f,
	0x93, 0x46, 0xd6, 0xd6, 0xae, 0x98, 0xc0, 0xaf, 0xd6, 0x7f, 0x60, 0xda, 0x0d, 0x64, 0x81, 0x7f,
	0xe0, 0xe5, 0xb7, 0xbe, 0xef, 0xb3, 0xf7, 0xed, 0x97, 0x42, 0xac, 0xb3, 0x73, 0x65, 0x38, 0x9a,
	0x91, 0x36, 0xca, 0x2a, 0x12, 0xea, 0x8c, 0x9e, 0x40, 0xf3, 0x8a, 0x73, 0x83, 0x45, 0x41, 0x8e,
	0xa0, 0xb5, 0x12, 0x3a, 0x79, 0x56, 0x1c, 0xfb, 0xc1, 0x20, 0x18, 0xb6, 0x59, 0x73, 0x25, 0xf4,
	0x54, 0x71, 0xa4, 0x13, 0xe8, 0xde, 0xe0, 0x5c, 0xbc, 0xa3, 0x59, 0xce, 0xe4, 0x8b, 0x32, 0x79,
	0x6a, 0x85, 0x92, 0xe4, 0x14, 0x9a, 0x69, 0x69, 0xf6, 0x86, 0x68, 0x1c, 0x8d, 0x74, 0x36, 0xaa,
	0x78, 0x6c, 0x7d, 0x46, 0xcf, 0x80, 0x3c, 0xa5, 0xcb, 0x1c, 0xa5, 0xdd, 0x36, 0xf7, 0xe0, 0xb7,
	0x55, 0xaf, 0x28, 0xab, 0x7f, 0x95, 0x03, 0x7d, 0x80, 0xbf, 0x8f, 0x2e, 0xe2, 0xbd, 0x90, 0x38,
	0xb3, 0x98, 0x93, 0x01, 0x74, 0x72, 0x94, 0x8b, 0x44, 0x58, 0xcc, 0x13, 0xc1, 0x2b, 0x35, 0xb8,
	0x6f, 0xee, 0x7c, 0xc6, 0xc9, 0x31, 0xb4, 0xde, 0x16, 0xa9, 0xb4, 0xc2, 0x2e, 0xfb, 0xe1, 0x20,
	0x18, 0x36, 0xd8, 0x66, 0xa6, 0xd7, 0x10, 0xd7, 0x70, 0x05, 0xb9, 0x00, 0x98, 0x0b, 0x89, 0x9e,
	0xe7, 0x62, 0x37, 0x86, 0xd1, 0xf8, 0xbf, 0x8b, 0x5d, 0xd3, 0xb1, 0xf6, 0x7c, 0xed, 0xa0, 0x1f,
	0x01, 0x44, 0x53, 0x83, 0xa9, 0x45, 0x2f, 0x21, 0x31, 0x84, 0x9b, 0x1c, 0xa1, 0xe0, 0xe4, 0x16,
	0xba, 0xba, 0xac, 0x97, 0x88, 0xef, 0x7e, 0x3e, 0x4a, 0x34, 0x3e, 0x70, 0xe8, 0xdd, 0xf6, 0x8c,
	0xe8, 0xdd, 0x1b, 0xb9, 0x83, 0x1e, 0xaf, 0x6e, 0xb9, 0x46, 0x6a, 0x78, 0xd2, 0xa1, 0x23, 0xed,
	0xd9, 0x02, 0xeb, 0xf2, 0x3d, 0xab, 0x99, 0xc0, 0x3f, 0xbf, 0xea, 0x64, 0xab, 0xec, 0x2f, 0xcf,
	0x21, 0x3b, 0x65, 0x0b, 0x16, 0xab, 0xda, 0x4c, 0x3f, 0x03, 0xe8, 0x78, 0x49, 0xd9, 0x9b, 0xff,
	0x80, 0xce, 0xd9, 0x1f, 0xff, 0x28, 0x2e, 0xbf, 0x02, 0x00, 0x00, 0xff, 0xff, 0x96, 0xab, 0xa9,
	0x49, 0x26, 0x03, 0x00, 0x00,
}
