version: '3.7'

services:
  ftgo-order:
    container_name: ftgo-order
    build:
      context: ../../
      dockerfile: Dockerfile
    depends_on:
      - ftgo-rabbitmq
      - ftgo-kitchen-mongo
    working_dir: /app/examples/ftgo/pkg/order
    volumes:
      - "../../:/app"
    ports:
      - "3000:3000"
    tty: true
  ftgo-order-postgres:
    container_name: ftgo-order-postgres
    image: postgres:12.1-alpine
    environment:
      POSTGRES_USER: ftgo
      POSTGRES_PASSWORD: ftgo123
      POSTGRES_DB: ftgo
    tty: true

  ftgo-kitchen:
    container_name: ftgo-kitchen
    build:
      context: ../../
      dockerfile: Dockerfile
    depends_on:
      - ftgo-rabbitmq
      - ftgo-kitchen-mongo
    working_dir: /app/examples/ftgo/pkg/kitchen
    volumes:
      - "../../:/app"
    ports:
      - "3001:3001"
    tty: true
  ftgo-kitchen-mongo:
    container_name: ftgo-kitchen-mongo
    image: mongo:4.2.2
    tty: true

  ftgo-restaurant:
    container_name: ftgo-restaurant
    build:
      context: ../../
      dockerfile: Dockerfile
    depends_on:
      - ftgo-rabbitmq
      - ftgo-restaurant-mongo
    working_dir: /app/examples/ftgo/pkg/restaurant
    volumes:
      - "../../:/app"
    ports:
      - "3002:3002"
    tty: true
  ftgo-restaurant-mongo:
    container_name: ftgo-restaurant-mongo
    image: mongo:4.2.2
    tty: true

  ftgo-rabbitmq:
    container_name: ftgo-rabbitmq
    image: rabbitmq:3.7-alpine
    tty: true
    ports:
      - "5672:5672"
      - "15672:15672"
