version: '3.7'

services:
  ftgo-order:
    container_name: ftgo-order
    build:
      context: ../../
      dockerfile: Dockerfile
    working_dir: /app/examples/ftgo/pkg/order
    volumes:
      - "../../:/app"
    ports:
      - "3000:3000"
    tty: true

  ftgo-order-postgres:
    container_name: ftgo-order-postgres
    image: postgres:12.1-alpine
    environment:
      POSTGRES_USER: ftgo
      POSTGRES_PASSWORD: ftgo123
      POSTGRES_DB: ftgo
    volumes:
      - "../../sql:/sql"
    tty: true

  rabbitmq:
    container_name: rabbitmq
    image: rabbitmq:3.7-alpine
    tty: true
