version: '3.7'

x-service-default: &service-default
  build:
    context: ../../
    dockerfile: Dockerfile
  depends_on:
    ftgo-rabbitmq:
  volumes:
    - "../../:/app"
  tty: true
  command:
    - /bin/bash
    - -c
    - |
      echo wait for rabbitmq to get ready
      sleep 20s
      make run

x-mongo-default: &mongo-default
  image: mongo:4.2.2
  tty: true

services:
  ftgo-order:
    <<: *service-default
    container_name: ftgo-order
    depends_on:
      - ftgo-kitchen-mongo
    working_dir: /app/examples/ftgo/pkg/order
    ports:
      - "3000:3000"
  ftgo-order-postgres:
    container_name: ftgo-order-postgres
    image: postgres:12.1-alpine
    environment:
      POSTGRES_USER: ftgo
      POSTGRES_PASSWORD: ftgo123
      POSTGRES_DB: ftgo
    tty: true

  ftgo-kitchen:
    <<: *service-default
    container_name: ftgo-kitchen
    depends_on:
      - ftgo-kitchen-mongo
    working_dir: /app/examples/ftgo/pkg/kitchen
    ports:
      - "3001:3001"
    command: /bin/bash
  ftgo-kitchen-mongo:
    <<: *mongo-default
    container_name: ftgo-kitchen-mongo

  ftgo-restaurant:
    <<: *service-default
    container_name: ftgo-restaurant
    depends_on:
      - ftgo-restaurant-mongo
    working_dir: /app/examples/ftgo/pkg/restaurant
    ports:
      - "3002:3002"
  ftgo-restaurant-mongo:
    <<: *mongo-default
    container_name: ftgo-restaurant-mongo

  ftgo-consumer:
    <<: *service-default
    container_name: ftgo-consumer
    depends_on:
      - ftgo-consumer-mongo
    working_dir: /app/examples/ftgo/pkg/consumer
    ports:
      - "3003:3003"
  ftgo-consumer-mongo:
    <<: *mongo-default
    container_name: ftgo-consumer-mongo

  ftgo-rabbitmq:
    container_name: ftgo-rabbitmq
    image: rabbitmq:3.7-alpine
    tty: true
    ports:
      - "5672:5672"
      - "15672:15672"
