settings:
  legacy:
    force: false
    interval: 0s
schema:
- name: kitchen
  path: .
  commands:
    install:
      status: true
      method: make build
    run:
      status: true
      method: ./bin/app
  watcher:
    extensions:
    - go
    paths:
    - /
    ignored_paths:
    - .git
    - .realize
    - vendor
