settings:
  legacy:
    force: false
    interval: 0s
schema:
- name: order
  path: .
  commands:
    install:
      status: true
      method: make build
    run:
      status: true
      method: make run
    test:
      status: true
  watcher:
    extensions:
    - go
    paths:
    - /
    ignored_paths:
    - .git
    - .realize
    - vendor
